const appname = "watchhub";
const appversion = "Version 1.0.0";
const credits = "@aptechfriends";
const email="Email";
const emailhint="admin@gmail.com";
const password="Password";
const passwordhint="*********";
const retypepass="Retype Password";
const name="Name";
const namehint="AptechFriends";
const forgetpassword="Forget Password";
const signup="Sign Up";
const login="Log In";
const create="or, create a new account";
const loginwith="login in with";
const privatepolicy="Privacy Policy";
const terms="Terms and Condition";
const already="Already have an account";
const home="Home",categories="Categories",cart="Cart",account="Account";
const searchanything="Search anything .....",todaydeal="Today's Deals",flashsale="Flash Sale",topseller="Top Sellers",brands="Brands",topcat="Top Categories",featurecat="Feature Categories";
const womencollection="Woman Collection";
const mancoll="Man Collection";
const smart="Smart Watches";
const mechanical="Mechanical Watches";
const solar="Solar Watches";
const royalcollect="Royal Collection";
const teenage="Teen Collection";
const bestselling="Best Seller";
const newarrival="New Arrival";
const Featured="Featured Product";

const bluegold="Blue Gold Chromatic";
const bluesport="Blue Sports WaterProof";
const simple="Simple and Elegant";
const goldstainless="Gold Staineless Steel";
const bluewithgolden="Blue with Golden Dial";
const blackforman="Black For Man";
const watchwithleather="Watch with Leather band";
const bluewithgolddial="Blue with Gold Dial";
const bluewithstainless="Blue With Stainless Steel";

